---
- name: Install dotfiles and packages
  hosts: localhost
  tasks:
    - name: install packages
      become: yes
      package:
        name: '{{ item }}'
        state: installed
      loop:
        - libselinux-python
        - git
        - vim
        - firefox
        - i3lock
        - htop
        - ranger
        - compton
        - fontawesome-fonts
        - xclip
        - pavucontrol
    - name: Source config and aliases
      lineinfile:
        path: '{{ item.path }}'
        line: '{{ item.line }}'
      loop:
        - { path: '~/.bashrc', line: 'source ~/dotfiles/bash_alias' }
        - { path: '~/.bashrc', line: 'source ~/dotfiles/bash_config' }
    - name: Create directories
      file:
        path: '{{ item.path }}'
        state: directory
        mode: 0755
      loop:
        - { path: '~/.config' }
        - { path: '~/.config/i3' }
    - name: Link files
      file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        state: link
        force: yes
      loop:
        - { src: '~/dotfiles/gitconfig', dest: '~/.gitconfig' }
        - { src: '~/dotfiles/vimrc', dest: '~/.vimrc' }
        - { src: '~/dotfiles/Xresources', dest: '~/.Xresources' }
        - { src: '~/dotfiles/config/compton.conf', dest: '~/.config/compton.conf' }
        - { src: '~/dotfiles/config/i3/config', dest: '~/.config/i3/config' }
