---
- name: Install dotfiles
  hosts: localhost
  tasks:
    - name: Clone / Update dotfiles repo
      git:
        repo: 'https://github.com/fxsn/dotfiles'
        dest: '~/dotfiles'
    - name: Source aliases in .bashrc
      lineinfile:
        path: '~/.bashrc'
        line: 'source ~/dotfiles/bash_alias'
    - name: Source config in .bashrc
      lineinfile:
        path: '~/.bashrc'
        line: 'source ~/dotfiles/bash_config'
    - name: Link .vimrc
      file:
        src: '~/dotfiles/vimrc'
        dest: '~/.vimrc'
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        state: link
    - name: Link .gitconfig
      file:
        src: '~/dotfiles/gitconfig'
        dest: '~/.gitconfig'
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        state: link
