- name: Create directories
  file:
    path: '{{ item.path }}'
    state: directory
    mode: 0755
    loop:
      - { path: '~/.config' }
      - { path: '~/.config/i3' }
      - { path: '~/.config/i3status' }